package com.nttdata.model.tmf;

public enum StartMode {

    UNKNOWN,
    AUTOMATICALLY_BY_THE_MANAGED_ENVIRONMENT,
    AUTOMATICALLY_BY_THE_OWNING_DEVICE,
    MANUALLY_BY_THE_PROVIDER_OF_THE_SERVICE,
    MANUALLY_BY_A_CUSTOMER_OF_THE_PROVIDER,
    ANY_OF_THE_ABOVE

}
